### ISSUE TITLE
Test Coverage Tracker

### ISSUE THREAD

**Issue by skmgoldin** [ConsenSys/PLCRVoting#15]
Test coverage in this repo is incomplete. If you would like to make a PR adding test coverage in the listed files, it will be reviewed and you will be lavished with praise for your work. Note that there is a nice [utils](https://github.com/ConsenSys/PLCRVoting/blob/master/test/utils.js) library to make your life easier!

- [x] [INITIAL_POLL_NONCE.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/INITIAL_POLL_NONCE.js)
- [x] [attrUUID.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/attrUUID.js)
- [x] [commitPeriodActive.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/commitPeriodActive.js)
- [x] [commitVote.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/commitVote.js)
- [ ] [getCommitHash.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getCommitHash.js)
- [x] [getInsertPointForNumTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getInsertPointForNumTokens.js)
- [ ] [getLastNode.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getLastNode.js)
- [ ] [getLockedTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getLockedTokens.js)
- [ ] [getNumPassingTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getNumPassingTokens.js)
- [ ] [getNumTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getNumTokens.js)
- [ ] [getTotalNumberOfTokensForWinningOption.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getTotalNumberOfTokensForWinningOption.js)
- [ ] [hasBeenRevealed.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/hasBeenRevealed.js)
- [ ] [isExpired.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/isExpired.js)
- [ ] [isPassed.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/isPassed.js)
- [x] [pollEnded.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/pollEnded.js)
- [ ] [pollExists.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/pollExists.js)
- [ ] [pollMap.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/pollMap.js)
- [ ] [pollNonce.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/pollNonce.js)
- [x] [requestVotingRights.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/requestVotingRights.js)
- [x] [rescueTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/rescueTokens.js)
- [ ] [revealPeriodActive.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/revealPeriodActive.js)
- [ ] [revealVote.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/revealVote.js)
- [ ] [startPoll.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/startPoll.js)
- [ ] [token.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/token.js)
- [x] [validPosition.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/validPosition.js)
- [ ] [voteTokenBalance.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/voteTokenBalance.js)
- [x] [withdrawVotingRights.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/withdrawVotingRights.js)

**Comment by kangarang** [comment]
I'll work on:
- [ ] `getLockedTokens.js`
- [ ] `getNumPassingTokens.js`
- [ ] `getNumTokens.js`
- [ ] `getTotalNumberOfTokensForWinningOption.js`

**Comment by skmgoldin** [comment]
I'm gonna add more files. There are getters that we don't have any pending coverage for.

**Comment by skmgoldin** [comment]
https://github.com/ConsenSys/PLCRVoting/commit/47efcb5c9fee8af6d4d96ffdf5fc493de61e42ab

There's pending coverage for everything now, including getters (If I missed anything lemme know). Updated the checklist.

**Comment by kangarang** [comment]
#16

**Comment by kangarang** [comment]
unchecking `revealVote` to account for various input values

https://github.com/ConsenSys/PLCRVoting/issues/28

**Comment by akuanti** [comment]
This is related to, but not identical to, #33. This issue attempts to track functions without any tests at all vs. functions that have at least one test.

**Comment by Kmoneal** [comment]
Deprecated due to #40.
