### ISSUE TITLE
Pending Tests Tracker

### ISSUE THREAD

**Issue by Kmoneal** [ConsenSys/PLCRVoting#40]
Updates #15 for EPM Version 1.1. These are the functions that still have pending tests.

Test coverage in this repo is incomplete. If you would like to make a PR adding test coverage in the listed files, it will be reviewed and you will be lavished with praise for your work. Note that there is a nice [utils](https://github.com/ConsenSys/PLCRVoting/blob/master/test/utils.js) library to make your life easier!

- [ ] [getCommitHash.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getCommitHash.js)
- [ ] [getLastNode.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getLastNode.js)
- [ ] [getLockedTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getLockedTokens.js)
- [ ] [getNumPassingTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getNumPassingTokens.js)
- [ ] [getNumTokens.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/getNumTokens.js)
- [ ] [isExpired.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/isExpired.js)
- [ ] [pollExists.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/pollExists.js)
- [ ] [pollMap.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/pollMap.js)
- [ ] [pollNonce.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/pollNonce.js)
- [ ] [revealPeriodActive.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/revealPeriodActive.js)
- [ ] [startPoll.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/startPoll.js)
- [ ] [token.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/token.js)
- [ ] [voteTokenBalance.js](https://github.com/ConsenSys/PLCRVoting/blob/master/test/voteTokenBalance.js)
